//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntSight.RayTracing.Language.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntSight.RayTracing.Language.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ambient definition..
        /// </summary>
        internal static string AmbientInvalid {
            get {
                return ResourceManager.GetString("AmbientInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background already defined..
        /// </summary>
        internal static string BackgroundAlreadyDefined {
            get {
                return ResourceManager.GetString("BackgroundAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid background definition..
        /// </summary>
        internal static string BackgroundInvalid {
            get {
                return ResourceManager.GetString("BackgroundInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera already defined..
        /// </summary>
        internal static string CameraAlreadyDefined {
            get {
                return ResourceManager.GetString("CameraAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blobs need three or more arguments..
        /// </summary>
        internal static string ParserBlobInsufficientParams {
            get {
                return ResourceManager.GetString("ParserBlobInsufficientParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; not found..
        /// </summary>
        internal static string ParserClassNotFound {
            get {
                return ResourceManager.GetString("ParserClassNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible constructor for class &apos;{0}&apos; not found..
        /// </summary>
        internal static string ParserConstructorNotFound {
            get {
                return ResourceManager.GetString("ParserConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob is not compatible with &apos;{0}&apos;..
        /// </summary>
        internal static string ParserIncompatibleBlob {
            get {
                return ResourceManager.GetString("ParserIncompatibleBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference is not compatible with &apos;{0}&apos;..
        /// </summary>
        internal static string ParserIncompatibleDifference {
            get {
                return ResourceManager.GetString("ParserIncompatibleDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection is not compatible with &apos;{0}&apos;..
        /// </summary>
        internal static string ParserIncompatibleIntersection {
            get {
                return ResourceManager.GetString("ParserIncompatibleIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Union is not compatible with &apos;{0}&apos;..
        /// </summary>
        internal static string ParserIncompatibleUnion {
            get {
                return ResourceManager.GetString("ParserIncompatibleUnion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points in an interpolation must either have times or not..
        /// </summary>
        internal static string ParserIncompleteInterpolationHints {
            get {
                return ResourceManager.GetString("ParserIncompleteInterpolationHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time hints in interpolation not in ascending order..
        /// </summary>
        internal static string ParserInterpolationNotAscending {
            get {
                return ResourceManager.GetString("ParserInterpolationNotAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid addition..
        /// </summary>
        internal static string ParserInvalidAdd {
            get {
                return ResourceManager.GetString("ParserInvalidAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid blob material..
        /// </summary>
        internal static string ParserInvalidBlobMaterial {
            get {
                return ResourceManager.GetString("ParserInvalidBlobMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid blob threshold..
        /// </summary>
        internal static string ParserInvalidBlobThreshold {
            get {
                return ResourceManager.GetString("ParserInvalidBlobThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character: &quot;{0}&quot;..
        /// </summary>
        internal static string ParserInvalidCharacter {
            get {
                return ResourceManager.GetString("ParserInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color brightness must be a real number..
        /// </summary>
        internal static string ParserInvalidColorBright {
            get {
                return ResourceManager.GetString("ParserInvalidColorBright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color components must be real numbers..
        /// </summary>
        internal static string ParserInvalidColorComp {
            get {
                return ResourceManager.GetString("ParserInvalidColorComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color name: {0}..
        /// </summary>
        internal static string ParserInvalidColorName {
            get {
                return ResourceManager.GetString("ParserInvalidColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid division..
        /// </summary>
        internal static string ParserInvalidDiv {
            get {
                return ResourceManager.GetString("ParserInvalidDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of parameters in function call..
        /// </summary>
        internal static string ParserInvalidFunctParamCount {
            get {
                return ResourceManager.GetString("ParserInvalidFunctParamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vector parameter in function call..
        /// </summary>
        internal static string ParserInvalidFunctVectorParam {
            get {
                return ResourceManager.GetString("ParserInvalidFunctVectorParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time hint in interpolation should always be 0.0..
        /// </summary>
        internal static string ParserInvalidInterpolationFirst {
            get {
                return ResourceManager.GetString("ParserInvalidInterpolationFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last time hint in interpolation should always be 1.0..
        /// </summary>
        internal static string ParserInvalidInterpolationLast {
            get {
                return ResourceManager.GetString("ParserInvalidInterpolationLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid multiplication..
        /// </summary>
        internal static string ParserInvalidMult {
            get {
                return ResourceManager.GetString("ParserInvalidMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positional parameter after named parameter in object {0}..
        /// </summary>
        internal static string ParserInvalidPositional {
            get {
                return ResourceManager.GetString("ParserInvalidPositional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid shear direction: {0}..
        /// </summary>
        internal static string ParserInvalidShear {
            get {
                return ResourceManager.GetString("ParserInvalidShear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid substraction..
        /// </summary>
        internal static string ParserInvalidSub {
            get {
                return ResourceManager.GetString("ParserInvalidSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unary expression..
        /// </summary>
        internal static string ParserInvalidUnary {
            get {
                return ResourceManager.GetString("ParserInvalidUnary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}, column {1}.
        /// </summary>
        internal static string ParserLineColPosFmt {
            get {
                return ResourceManager.GetString("ParserLineColPosFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}.
        /// </summary>
        internal static string ParserLinePosFmt {
            get {
                return ResourceManager.GetString("ParserLinePosFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}, columns {1}-{2}.
        /// </summary>
        internal static string ParserLineRangeFmt {
            get {
                return ResourceManager.GetString("ParserLineRangeFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong parameter count expanding macro &apos;{0}&apos;..
        /// </summary>
        internal static string ParserMacroParamsMismatch {
            get {
                return ResourceManager.GetString("ParserMacroParamsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material definition not included..
        /// </summary>
        internal static string ParserMissingMaterial {
            get {
                return ResourceManager.GetString("ParserMissingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class &apos;{0}&apos; should implement interface &apos;{1}&apos;..
        /// </summary>
        internal static string ParserNotImplemented {
            get {
                return ResourceManager.GetString("ParserNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter mismatch in constructor for class &apos;{0}&apos;..
        /// </summary>
        internal static string ParserParamMismatch {
            get {
                return ResourceManager.GetString("ParserParamMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing aborted..
        /// </summary>
        internal static string ParserParsingAborted {
            get {
                return ResourceManager.GetString("ParserParsingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range expression needs two or more parameters..
        /// </summary>
        internal static string ParserRangeInsufficientParams {
            get {
                return ResourceManager.GetString("ParserRangeInsufficientParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type in range expression parameters..
        /// </summary>
        internal static string ParserRangeInvalidParamType {
            get {
                return ResourceManager.GetString("ParserRangeInvalidParamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times in a range expression must evaluate to real numbers..
        /// </summary>
        internal static string ParserRangeTimeNotReal {
            get {
                return ResourceManager.GetString("ParserRangeTimeNotReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not supported in interpolation function..
        /// </summary>
        internal static string ParserRangeUnsupportedType {
            get {
                return ResourceManager.GetString("ParserRangeUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error..
        /// </summary>
        internal static string ParserSyntaxError {
            get {
                return ResourceManager.GetString("ParserSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown identifier: {0}..
        /// </summary>
        internal static string ParserUnknownID {
            get {
                return ResourceManager.GetString("ParserUnknownID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render already in progress..
        /// </summary>
        internal static string RenderIsBusy {
            get {
                return ResourceManager.GetString("RenderIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampler already defined..
        /// </summary>
        internal static string SamplerAlreadyDefined {
            get {
                return ResourceManager.GetString("SamplerAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no camera definition!.
        /// </summary>
        internal static string SceneNoCamera {
            get {
                return ResourceManager.GetString("SceneNoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene title already defined..
        /// </summary>
        internal static string TitleAlreadyDefined {
            get {
                return ResourceManager.GetString("TitleAlreadyDefined", resourceCulture);
            }
        }
    }
}
