//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntSight.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntSight.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bkmark08 {
            get {
                object obj = ResourceManager.GetObject("bkmark08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bkmark12 {
            get {
                object obj = ResourceManager.GetObject("bkmark12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bkmark14 {
            get {
                object obj = ResourceManager.GetObject("bkmark14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap first {
            get {
                object obj = ResourceManager.GetObject("first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fit {
            get {
                object obj = ResourceManager.GetObject("fit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid line number, please..
        /// </summary>
        internal static string GotoLineEnterValidLine {
            get {
                return ResourceManager.GetString("GotoLineEnterValidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number can&apos;t be lesser than 1..
        /// </summary>
        internal static string GotoLineLineLesserThanOne {
            get {
                return ResourceManager.GetString("GotoLineLineLesserThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number is not an integer value..
        /// </summary>
        internal static string GotoLineLineNotInteger {
            get {
                return ResourceManager.GetString("GotoLineLineNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number can&apos;t be greater than {0}..
        /// </summary>
        internal static string GotoLineLineTooHigh {
            get {
                return ResourceManager.GetString("GotoLineLineTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap last {
            get {
                object obj = ResourceManager.GetObject("last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MruFileList capacity too low: {0}..
        /// </summary>
        internal static string MruListCapacityTooLow {
            get {
                return ResourceManager.GetString("MruListCapacityTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previous {
            get {
                object obj = ResourceManager.GetObject("previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}.
        /// </summary>
        internal static string ScrollBarLineFormat {
            get {
                return ResourceManager.GetString("ScrollBarLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        internal static string UndoCmdComment {
            get {
                return ResourceManager.GetString("UndoCmdComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletion.
        /// </summary>
        internal static string UndoCmdDeletion {
            get {
                return ResourceManager.GetString("UndoCmdDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drag copy.
        /// </summary>
        internal static string UndoCmdDragCopy {
            get {
                return ResourceManager.GetString("UndoCmdDragCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drag move.
        /// </summary>
        internal static string UndoCmdDragMove {
            get {
                return ResourceManager.GetString("UndoCmdDragMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indent.
        /// </summary>
        internal static string UndoCmdIndent {
            get {
                return ResourceManager.GetString("UndoCmdIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outdent.
        /// </summary>
        internal static string UndoCmdOutdent {
            get {
                return ResourceManager.GetString("UndoCmdOutdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paste.
        /// </summary>
        internal static string UndoCmdPaste {
            get {
                return ResourceManager.GetString("UndoCmdPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replacement.
        /// </summary>
        internal static string UndoCmdReplace {
            get {
                return ResourceManager.GetString("UndoCmdReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to snippet expansion.
        /// </summary>
        internal static string UndoCmdSnippet {
            get {
                return ResourceManager.GetString("UndoCmdSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text transform.
        /// </summary>
        internal static string UndoCmdTransform {
            get {
                return ResourceManager.GetString("UndoCmdTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typing.
        /// </summary>
        internal static string UndoCmdTyping {
            get {
                return ResourceManager.GetString("UndoCmdTyping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove comments.
        /// </summary>
        internal static string UndoCmdUncomment {
            get {
                return ResourceManager.GetString("UndoCmdUncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom100 {
            get {
                object obj = ResourceManager.GetObject("zoom100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
